NETWORK:
  INPUTS: 784
  HIDDEN_LAYERS:
    - [ 64, 'ReLU' ]
    - [ 32, 'ReLU' ]
  OUTPUTS: 10
DATASET:
  NAME: mnist
  PATH: ./data/mnist
  NORMALIZE: True
TRAINING:
  LOSS: crossentropy
  EPOCHS: 40
  BATCH_SIZE: 100
  LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  HOLDOUT: 0.1
